services:
  - type: web
    name: roof-lidar-backend
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker --timeout 120"
    plan: free
    autoDeploy: yes
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
